In [1]:
from skimage import io
import numpy as np
import os

# 前處理

In [2]:
img_list = list()
img_list_np = np.array(img_list)
for dirPath, dirNames, fileNames in os.walk('Aberdeen'):
    for i, f in enumerate(fileNames):
        loadFile = os.path.join(dirPath, f)
        img = io.imread(loadFile)
        img_np = np.array(img)
        img_fla = img_np.flatten()
#         print(img_np.shape)
        img_fla = img_fla.reshape(1,1080000)
#         print(img_fla)
        if i == 0:
            img_list_np = img_fla
        else:
#             print(img_list_np)
            img_list_np = np.concatenate((img_list_np, img_fla), axis=0)
img_list_np = img_list_np.T
print(img_list_np)

[[255 255 255 ..., 255 254 255]
 [254 255 255 ..., 255 254 255]
 [249 253 255 ..., 255 228 232]
 ..., 
 [  1   1   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   1]
 [  0   2   0 ...,  19   0   0]]


In [3]:
img_mean = np.mean(img_list_np)
print(img_mean)
print(img_list_np.shape)

157.02426757
(1080000, 415)


In [4]:
img_mean_np = np.ones(448200000,)
img_mean_np = img_mean_np.reshape(1080000, 415)
img_mean_np = img_mean_np * img_mean
print(img_mean_np)
X = img_list_np - img_mean_np
# img_list_np = img_list_np.reshape(600,600,3,415)
U, s, V = np.linalg.svd(X, full_matrices=False)

[[ 157.02426757  157.02426757  157.02426757 ...,  157.02426757
   157.02426757  157.02426757]
 [ 157.02426757  157.02426757  157.02426757 ...,  157.02426757
   157.02426757  157.02426757]
 [ 157.02426757  157.02426757  157.02426757 ...,  157.02426757
   157.02426757  157.02426757]
 ..., 
 [ 157.02426757  157.02426757  157.02426757 ...,  157.02426757
   157.02426757  157.02426757]
 [ 157.02426757  157.02426757  157.02426757 ...,  157.02426757
   157.02426757  157.02426757]
 [ 157.02426757  157.02426757  157.02426757 ...,  157.02426757
   157.02426757  157.02426757]]


In [5]:
print(U.shape)
print('________________________________')
print(s.shape)
print('________________________________')
print(V.shape)

(1080000, 415)
________________________________
(415,)
________________________________
(415, 415)


In [6]:
sigma = np.diag(s)
print(sigma.shape)
print('________________________________')
print(s)

(415, 415)
________________________________
[  1.02633666e+06   5.08958552e+05   3.84407712e+05   3.11156708e+05
   2.70624664e+05   2.63014057e+05   2.41247767e+05   2.06636554e+05
   1.92187401e+05   1.86400638e+05   1.58635328e+05   1.36467164e+05
   1.28898615e+05   1.26375874e+05   1.16400080e+05   1.14426320e+05
   1.13430283e+05   1.09571203e+05   1.07443277e+05   1.02298185e+05
   9.83500973e+04   9.44242026e+04   9.04904618e+04   8.93615599e+04
   8.72448253e+04   8.35828190e+04   8.24203888e+04   8.07138119e+04
   7.88609607e+04   7.75711822e+04   7.48576903e+04   7.35074744e+04
   7.22553507e+04   7.12705626e+04   6.78211264e+04   6.66852714e+04
   6.61750846e+04   6.50242496e+04   6.31951393e+04   6.21428076e+04
   6.10933542e+04   5.93890703e+04   5.92117967e+04   5.75513230e+04
   5.65922592e+04   5.64681686e+04   5.56543010e+04   5.52844026e+04
   5.37961436e+04   5.32241538e+04   5.24674261e+04   5.16496648e+04
   5.13167761e+04   4.99798828e+04   4.98146905e+04   4.921

In [7]:
test_img = io.imread('Aberdeen/0.jpg')
test_img_np = np.array(test_img)
test_img_fla = test_img_np.flatten()
print(test_img_fla)
print(test_img_fla.shape)
weight = list()
for column in range(415):
    weight.append(np.dot(test_img_fla, U.T[column]))
# image = np.dot(U, np.dot(sigma, V))

[255 254 249 ...,   1   0   0]
(1080000,)


In [8]:
weight_np = np.array(weight)
print(weight_np)
eigenfaces = np.zeros(1080000,)
eigenface = np.zeros(1080000,)
for column, w in enumerate(weight_np):
    eigenfaces += w * U.T[column]
#     if column == 9:
#         eigenface = w * U.T[column]
#         print(9)
    if column == 10:
        eigenface = w * U.T[column]
        print(10)

print('_______________________________________________________')
test_img_mean_np = np.ones(1080000,)
test_img_mean_np = test_img_mean_np * img_mean
eigenfaces += test_img_mean_np
print(eigenfaces)

print('_______________________________________________________')
eigenface += test_img_mean_np
print(eigenface)

[ -6.23112070e+04   7.43053323e+04   4.45980628e+03   6.59287630e+04
   6.37587222e+04  -2.65444772e+04  -1.56815214e+04   4.52865837e+03
  -4.19986969e+04  -1.50640294e+04  -1.56462133e+04   8.25177426e+03
  -1.09159613e+04   3.28689292e+03  -4.82201940e+03  -3.40866482e+03
   5.13430155e+03  -6.05936126e+03   9.48611427e+02  -7.63734138e+03
  -1.13375563e+04   4.39907984e+03  -5.24344940e+03  -8.03239038e+03
  -8.81735637e+03  -1.96197027e+03  -4.55733178e+03  -4.21421478e+03
  -5.47643549e+03   1.78090676e+03  -1.19807767e+04  -7.80401879e+02
   7.34591045e+03   6.10315356e+03  -9.16565639e+03   4.28295880e+03
   3.95772612e+03  -2.00919894e+02  -8.32158899e+03  -1.79950388e+03
   2.08489605e+03  -8.67350258e+02  -5.88579247e+03   7.15351503e+03
  -7.59261621e+03   4.24360765e+03   2.12913896e+03   6.50168850e+03
  -4.96505468e+02   1.00056880e+04  -2.84102682e+03   2.58415180e+03
  -7.99927787e+01   1.87944508e+03  -1.02081779e+03   2.64627359e+03
  -4.11857635e+03   1.75076978e+02

In [9]:
eigenfaces -= np.min(eigenfaces)
eigenfaces /= np.max(eigenfaces)
eigenfaces = (eigenfaces*255).astype(np.uint8)

eigenface -= np.min(eigenface)
eigenface /= np.max(eigenface)
eigenface = (eigenface*255).astype(np.uint8)

In [10]:
print(eigenfaces)
print(eigenface)

[135 150 180 ...,   5   7  10]
[131 131 129 ...,  97  98  97]


In [11]:
eigenfaces = eigenfaces.reshape(600, 600, 3)
print(eigenfaces)
io.imsave('output.jpg', eigenfaces)

print('_______________________________________________________')

eigenface = eigenface.reshape(600, 600, 3)
print(eigenface)
eigenface = -eigenface
io.imsave('11th.jpg', eigenface)

[[[135 150 180]
  [146 151 190]
  [142 151 188]
  ..., 
  [167 174 190]
  [155 160 173]
  [  5   7   7]]

 [[135 143 180]
  [144 152 189]
  [143 152 189]
  ..., 
  [168 174 190]
  [156 160 173]
  [  4   7   7]]

 [[135 144 180]
  [144 152 189]
  [142 152 188]
  ..., 
  [169 175 191]
  [157 161 174]
  [  4   7   7]]

 ..., 
 [[171 172 160]
  [164 164 153]
  [158 158 147]
  ..., 
  [121 124 140]
  [109 111 125]
  [  3   7   9]]

 [[159 158 152]
  [152 152 146]
  [147 146 140]
  ..., 
  [121 122 135]
  [102 106 116]
  [ 11  15  21]]

 [[  5   7   8]
  [  4   6   7]
  [  5   6   8]
  ..., 
  [  5   8  10]
  [ 12  16  22]
  [  5   7  10]]]
_______________________________________________________
[[[131 131 129]
  [133 133 131]
  [134 134 132]
  ..., 
  [188 187 182]
  [196 195 191]
  [ 99  98  98]]

 [[131 132 129]
  [133 133 131]
  [133 133 131]
  ..., 
  [188 186 181]
  [196 194 191]
  [ 99  98  98]]

 [[132 132 130]
  [132 133 130]
  [133 133 131]
  ..., 
  [187 185 180]
  [194 193 189]
 